### ISSUE TITLE
Format differs depending on @media context

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [SeanJM/css-clean#17]
Formatting these two examples produces differing results. Each example shows the final layout; one obvious difference is the lack of new line characters in between blocks.

**With @media ...**
```css
@media handheld,
       only screen and (max-width: 760px) {
  .no-mobile {
    display : none;
  }
    /*Turns off grey BG behind logo*/
  nav.main {
    background-color : transparent;
  }
  nav.main a {
    color : #000;
  }
    /*Make quicklinks dropdown big*/
  #site_navigation {
    width  : 100%;
    height : 2.5em;
    margin : 0;
  }
  .image-select {
    width  : 100%;
    margin : 0 0 2em 0;
  }
  .image-select .container {
    margin : 0 auto;
  }
  nav.big {
    display : none;
  }
}

```

**Without @media...**
```css
.no-mobile {
  display : none;
}

/*Turns off grey BG behind logo*/

nav.main {
  background-color : transparent;
}

nav.main a {
  color : #000;
}

/*Make quicklinks dropdown big*/

#site_navigation {
  width  : 100%;
  height : 2.5em;
  margin : 0;
}

.image-select {
  width  : 100%;
  margin : 0 0 2em 0;
}

.image-select .container {
  margin : 0 auto;
}

nav.big {
  display : none;
}

```

I would expect the result to look more like the "without @media" example.
