### ISSUE TITLE
Removes css variables in root

### ISSUE THREAD

**Issue by dyskette** [SeanJM/css-clean#3]
They are just gone when applying css-clean on a css file.

Example:
```css
:root {
  --main-bg: #263238;
  --main-text: #eceff1;
}
```

Results:
```css
:root {}
```

Reproducible: Always
Atom version: 1.15.0
css-clean version: 2.19.0
