### ISSUE TITLE
Removing unknown statements

### ISSUE THREAD

**Issue by NiB18** [SeanJM/css-clean#5]
Not sure if it's issue, but it seems that plugins is removing unknown statements. For example it removes -webkit-font-smoothing statement. Can this be changed or is there any setting for a plugin?

Thanks!

**Comment by SeanJM** [comment]
Yep. The way it does property detection, that will occur when ever it doesn't recognize a property. I added `-webkit-font-smoothing` to the properties list. So that won't remove it anymore. Any properties that you run into, just post it and I'll add them.

**Comment by NiB18** [comment]
Thanks for prompt response and solution! 
Would it not be better if it just ignores property if it doesn't recognise it? Otherwise I can't use it in production because I can't risk that some property will be deleted and I won't notice.

**Comment by SeanJM** [comment]
Eventually yes. Keep in mind that if a new property is added to the list, it will work fine. Did you look at the list of properties and find any holes?

**Comment by eyecatchup** [comment]
@SeanJM There seem to be some more that are not on the properties list. 

Here's (part of) a basic CSS reset I use; before using `css-clean`.
 
```css
* {
    box-sizing: border-box;
    -webkit-device-pixel-ratio: 1;
    -webkit-tap-highlight-color: transparent;
    -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
}

body,
html {
    background: white;
    color: #444;
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    min-width: 320px;
    min-height: 100%;
    font-display: optional;
    font-family: 'Helvetica', 'Arial', 'Verdana', sans-serif;
    font-weight: 400;
    font-size: 1em;
    line-height: 1.4;
    -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
    -moz-osx-font-smoothing: grayscale;
     -webkit-font-smoothing: antialiased;
}

html {
    overflow: hidden;
    -ms-touch-action: manipulation;
        touch-action: manipulation;
}

body {
    background: #ececec;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
        -ms-flex-direction: column;
            flex-direction: column;
    -webkit-flex-wrap: nowrap;
        -ms-flex-wrap: nowrap;
            flex-wrap: nowrap;
    -webkit-box-pack: start;
       -ms-flex-pack: start;
    -webkit-justify-content: flex-start;
            justify-content: flex-start;
    -webkit-box-align: stretch;
    -webkit-align-items: stretch;
         -ms-flex-align: stretch;
            align-items: stretch;
    -webkit-align-content: stretch;
       -ms-flex-line-pack: stretch;
            align-content: stretch;
}

img {
    -ms-interpolation-mode: bicubic;
}

a,
h1,
h2,
h3,
h4,
h5,
h6  {
    -webkit-margin-before: 0;
    -webkit-margin-after: 0;
    -webkit-margin-start: 0;
    -webkit-margin-end: 0;
}

```
And that's what's left after using `css-clean`:

```css
* {
    box-sizing : border-box;
}

body,
html {
    width      : 100%;
    min-width  : 320px;
    height     : 100%;
    min-height : 100%;
    margin     : 0;
    padding    : 0;
    color      : #444;
    background : white;
}

html {
    overflow : hidden;
}

body {
    display    : -webkit-box;
    display    : -webkit-flex;
    display    : -ms-flexbox;
    display    : flex;
    background : #ececec;
}

img {}

a,
h1,
h2,
h3,
h4,
h5,
h6 {}

```

<hr>

**1.** Note that `css-clean` not only removed all the new fancy, prefixed props, but also all font definition from the body, and even the `line-height`!? Any idea what's wrong here? _This_ should in no way be related to the unknown properties thing..

**2.** As for the missing properties; here's the (alphabetically sorted) list of missing properties:

#### Vendor-prefixed properties

- `-webkit-align-content`
- `-webkit-align-items`
- `-webkit-box-align`
- `-webkit-box-direction`
- `-webkit-box-orient`
- `-webkit-box-pack`
- `-webkit-device-pixel-ratio`
- `-webkit-flex-direction`
- `-webkit-flex-wrap`
- `-webkit-font-smoothing`
- `-webkit-justify-content`
- `-webkit-margin-before`
- `-webkit-margin-after`
- `-webkit-margin-start`
- `-webkit-margin-end`
- `-webkit-tap-highlight-color`
- `-webkit-text-size-adjust`
- `-ms-flex-align`
- `-ms-flex-direction`
- `-ms-flex-line-pack`
- `-ms-flex-pack`
- `-ms-flex-wrap`
- `-ms-interpolation-mode`
- `-ms-text-size-adjust`
- `-ms-touch-action`
- `-moz-osx-font-smoothing`

#### Standard properties

- `align-content`
- `align-items`
- `flex-direction`
- `flex-wrap`
- `font-display`
- `justify-content`
- `touch-action`
