### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scope' of undefined [Please include CSS in bug report]

### ISSUE THREAD

**Issue by vpakg** [SeanJM/css-clean#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: elementary OS
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'scope' of undefined

```
At /home/vpakg/.atom/packages/css-clean/main.js:830

TypeError: Cannot read property 'scope' of undefined
    at Function.capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.sortCss.scope (/home/victor/.atom/packages/css-clean/main.js:830:28)
    at sortDeep (/home/victor/.atom/packages/css-clean/main.js:779:13)
    at sortCss (/home/victor/.atom/packages/css-clean/main.js:812:9)
    at capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.cleanCss.fn.value (/home/victor/.atom/packages/css-clean/main.js:487:3)
    at Object.value (/home/victor/.atom/packages/css-clean/main.js:1279:29)
    at atom-text-editor.capture.property group.capture.sass each.capture.sass for.capture.sass import.capture.sass mixin.getValue.selector.getValue.comment block.getValue.media query.getValue.sass import.getValue.shared.nested.lines.map.value.split.map.module.exports.convert (/home/victor/.atom/packages/css-clean/main.js:1393:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:28.2.0 tree-view:duplicate (span.name.icon.icon-file-text)
     -2:25.5.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -2:23.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -2:14.7.0 core:delete (atom-text-editor.editor.is-focused)
     -1:46.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.5.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel.ignore-hidden)
     -1:10.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.1.0 clipboard-history:copy (atom-text-editor.editor.is-focused)
     -1:03.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:03.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:45 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:44.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:40.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:02.0 css-clean:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "php-cs-fixer",
      "jscs-fixer",
      "merge-conflicts",
      "sync-settings"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
atom-minify, v0.7.1
atom-ternjs, v0.13.2
auto-indent, v0.5.0
autoclose-html, v0.23.0
bottom-dock, v0.3.7
clipboard-history, v0.6.6
color-picker, v2.1.1
css-clean, v2.2.4
css-snippets, v0.9.0
css-spy, v0.5.1
docs-snippets, v0.8.0
emmet, v2.4.2
git-hide, v0.1.2
jQuery, v1.2.3
jquery-snippets, v11.0.0
language-blade, v0.23.0
language-gitignore, v0.2.0
language-htaccess, v0.1.1
language-todo-extra-words, v0.2.0
laravel, v0.7.0
laravel-snippets, v2.1.0
linter, v1.11.3
linter-js-standard, v3.2.1
linter-manager, v0.2.9
linter-php, v1.2.0
local-history, v3.2.3
minimap, v4.21.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-pigments, v0.2.0
navigate, v0.1.13
pigments, v0.24.5
project-manager, v2.7.6
seti-icons, v0.4.5
symbols-tree-view, v0.11.0
todo-manager, v0.2.6
tool-bar, v0.3.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
Can you post your CSS?

**Comment by SeanJM** [comment]
It would really serve everyones interest if you post your CSS.

**Comment by SeanJM** [comment]
Victor, we live in the same city. I am going to come over to your house and get that CSS. You ever go to HackerNest?

**Comment by vpakg** [comment]
Hey @SeanJM sorry for the delay. I haven't been to HackerNest, but now I'll definitely look at it.

I was testing the script on a plugin's CSS (PaceJs):

```css
.pace {
    -webkit-pointer-events: none;
    pointer-events: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
}

.pace-inactive {
    display: none;
}

.pace .pace-progress {
    background: #bdbaff;
    position: fixed;
    z-index: 2000;
    top: 0;
    right: 100%;
    width: 100%;
    height: 2px;
}

.pace .pace-progress-inner {
    display: block;
    position: absolute;
    right: 0px;
    width: 100px;
    height: 100%;
    box-shadow: 0 0 10px #bdbaff, 0 0 5px #bdbaff;
    opacity: 1.0;
    -webkit-transform: rotate(3deg) translate(0px, -4px);
    -moz-transform: rotate(3deg) translate(0px, -4px);
    -ms-transform: rotate(3deg) translate(0px, -4px);
    -o-transform: rotate(3deg) translate(0px, -4px);
    transform: rotate(3deg) translate(0px, -4px);
}

.pace .pace-activity {
    display: block;
    position: fixed;
    z-index: 2000;
    top: 15px;
    right: 15px;
    width: 14px;
    height: 14px;
    border: solid 2px transparent;
    border-top-color: #bdbaff;
    border-left-color: #bdbaff;
    border-radius: 10px;
    -webkit-animation: pace-spinner 400ms linear infinite;
    -moz-animation: pace-spinner 400ms linear infinite;
    -ms-animation: pace-spinner 400ms linear infinite;
    -o-animation: pace-spinner 400ms linear infinite;
    animation: pace-spinner 400ms linear infinite;
}

@-webkit-keyframes pace-spinner {
    0% { -webkit-transform: rotate(0deg); transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); transform: rotate(360deg); }
}
@-moz-keyframes pace-spinner {
    0% { -moz-transform: rotate(0deg); transform: rotate(0deg); }
    100% { -moz-transform: rotate(360deg); transform: rotate(360deg); }
}
@-o-keyframes pace-spinner {
    0% { -o-transform: rotate(0deg); transform: rotate(0deg); }
    100% { -o-transform: rotate(360deg); transform: rotate(360deg); }
}
@-ms-keyframes pace-spinner {
    0% { -ms-transform: rotate(0deg); transform: rotate(0deg); }
    100% { -ms-transform: rotate(360deg); transform: rotate(360deg); }
}
@keyframes pace-spinner {
    0% { transform: rotate(0deg); transform: rotate(0deg); }
    100% { transform: rotate(360deg); transform: rotate(360deg); }
}
```

Great job, btw :+1:
